language: go

go:
- '1.13'
- '1.14'
- '1.15'
- 'stable' # the latest version will be always checked
addons:
  apt:
    packages: rpm
install:
  - gem install fpm -v 1.8.1

script:
- make
- make test

before_deploy:
- go get github.com/mitchellh/gox
- make gox-build
- make fpm-deb
- make fpm-rpm

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: uT79l9CW1wnakJFAWrA8AXV3lqGcXIICFkPJSuoeb3z8wgDhwxxXyn5ocKFcAZPJnlo9TFNffRCy71h7PogEmb/H8u45lKVFkviIgljs9pkvLAXJr1Wajqg5d5vOLVyNvzWKqdx7s7vunk+AJ1JFiQzY0lYKwUbwA+Yo8vKRbpNULhJPs11Wvz4wkJw6LyPCg752PAnObnWk1763Q6Q3bMe+uoQVF0fqP7+2Q7Zlg/ZX/m+mtiYPMF7X92rTF/on+ueepgpbZ+g5iT/NBnGPhRZWvBtbT3n91BhrLeHl9dNTILLkCbCgMpkG81VKrT9MyqardTKvzaaAXKwdtvC4Tn3duD5A7KIIMq4D4eZOKI5pIVnoDVr/GwJM1y3F2nBOOKX4tBMYTjTOHG1attEHIF0RzljFQVLHtEX2MNj/6hzcEv5+RB13VwV6KenT7MS7soVr9jvsrSYDL/ZU1ozf4mZkwdOSEorunTVUEeXzTeuxcVk3VkT0/X7CmW0ZClfvK/Ny432bKWzT3FlRvdyaISd4gD1j0d0MvDH9WqznrCFDkTqsLxNXNxvz52QEgfU681FjOf5yXy9fnuU+QnHitHWytNZJ7SmjIWB0K7sEWNrQ3qW+LGdBJ/QoAFcIel56y1wIQhf6ZqhCsx+vzy7GkwL1xnPQuxyNZisd9XpwFWI=
  file_glob: true
  file:
    - "*.{deb,rpm}"
  on:
    repo: lomik/carbon-clickhouse
    tags: true
